# Generated by Django 4.2.9 on 2024-01-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_average_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='big_mac_dollar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='currency_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='currency_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='exchange_rate_dollar',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='ppp_usa',
            field=models.FloatField(null=True),
        ),
    ]
